version: "3.9"
services:
  web:
    build: .
    volumes:
      - ./pages:/app/pages
      - ./public:/app/public
      - ./styles:/app/styles
    ports:
      - "8080:8080"
  postgres:
    image: postgres:latest
    restart: always
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
    volumes:
      - postgres:/var/lib/postgresql/data
    ports:
      - "5432:5432"
volumes:
  postgres:
